action = "create"
version = 1
schema = "schema_definition_v1"

[fields.name]
type = "str"
value = "event"

[fields.description]
type = "str"
value = "An event in a historical venue"

[fields.fields]
type = "pinned_relation_list"
value = [
  ["00202a7945458f109191f5bfb5877ceb95b866032967518fc4166538b5a7bf5f430a"],
  ["00207287306628c325973dc5973b5de1a330b287b08d3e3de99b6ecfa87cd52b23e0"],
]
