action = "create"
version = 1
schema = "schema_field_definition_v1"

[fields.name]
type = "str"
value = "venue"

[fields.type]
type = "str"
value = "pinned_relation(venue_002020da00fe6fb680537b4f46858ca5e9ceb45983401cdad8abf1477330c9ce9fdc)"
